name: Terraform Deploy to Dev

on:
  push:
    branches:
      - "**"
      - "!dev"
      - "!test"
      - "!main"
  workflow_dispatch:
    branches:
        - "**"
        - "!dev"
        - "!test"
        - "!main"

jobs:
  deploy:
    name: Deploy
    environment: ${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest

    steps:
        - name: Nowt
          run: echo "Nowt"

        - name: Delete Deployment Environment  
          uses: strumwolf/delete-deployment-environment@v2.3.0
          with:
            environment: ${{ github.head_ref || github.ref_name }}
            token: ${{ github.token }}