name: Terraform Deploy to Dev

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    environment: ${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest

    steps:
        - name: Nowt
          run: echo "Nowt"
