name: Terraform Deploy to Dev

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    environment: ${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      nowt:
        name: Nowt
        run: echo "Nowt"
